-- Arquivo de Schema para o projeto SimulaBET
-- Este script cria todas as tabelas e políticas de segurança (RLS).
-- Para usar: copie e cole todo o conteúdo no SQL Editor do seu projeto Supabase e clique em "RUN".

-- Tabela para guardar os perfis dos usuários
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  saldo NUMERIC DEFAULT 1000,
  data_ultimo_reset_saldo TIMESTAMPTZ DEFAULT now(),
  username TEXT
);
COMMENT ON TABLE public.profiles IS 'Armazena dados de perfil para cada usuário.';

-- Tabela para guardar os jogos buscados da API
CREATE TABLE public.game (
  fixture_id TEXT PRIMARY KEY,
  team_house TEXT,
  team_away TEXT,
  date_time TIMESTAMPTZ,
  result TEXT,
  odds_home NUMERIC,
  odds_draw NUMERIC,
  odds_away NUMERIC,
  created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.game IS 'Armazena os jogos e odds buscados da API externa.';

-- Tabela para guardar as apostas dos usuários
-- Nota: O nome "Aposta" com A maiúsculo requer aspas duplas no SQL.
CREATE TABLE public."Aposta" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  user_id UUID REFERENCES public.profiles(id),
  fixture_id TEXT REFERENCES public.game(fixture_id),
  palpite TEXT,
  valor_apostado NUMERIC,
  odds NUMERIC,
  status TEXT DEFAULT 'pendente'
);
COMMENT ON TABLE public."Aposta" IS 'Registra cada aposta feita por um usuário.';


--- POLÍTICAS DE SEGURANÇA (RLS) ---

-- Habilita RLS em todas as tabelas
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Aposta" ENABLE ROW LEVEL SECURITY;

-- Políticas para a tabela 'profiles'
CREATE POLICY "Usuários podem ver e gerenciar seu próprio perfil" ON public.profiles
FOR ALL USING (auth.uid() = id);

-- Políticas para a tabela 'game'
CREATE POLICY "Qualquer usuário logado pode ver os jogos" ON public.game
FOR SELECT TO authenticated USING (true);

-- Políticas para a tabela 'Aposta'
CREATE POLICY "Usuários podem ver suas próprias apostas" ON public."Aposta"
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem criar suas próprias apostas" ON public."Aposta"
FOR INSERT WITH CHECK (auth.uid() = user_id);